#Constants used in our project
PROFILE_TOP_FRIENDS_COUNT = 10
NORMALIZE_VALUE = 5 #Range 0-5 for each factor we are considering for suggestions


PER_FRIEND_SUGGESTIONS_COUNT = 5 
TOTAL_SUGGESTIONS_COUNT = 20 

#Suggestions first round percent weightages for getting close friends
MUTUAL_FRIEND_WEIGHTAGE_1 = 15
WORKPLACE_WEIGHTAGE_1 = 10
EDUCATION_WEIGHTAGE_1 = 10
COMMENTED_POSTS_WEIGHTAGE_1 = 15
LIKED_POSTS_WEIGHTAGE_1 = 10
COAPPEARANCE_WEIGHTAGE_1 = 15
PROFILE_VISITS_WEGIHTAGE_1 = 15
CURRENT_LOCATION_WEIGHTAGE_1 = 5
HOMETOWN_WEIGHTAGE_1 = 5

#Suggestions second round percent weightages for getting similar friends of close friends
MUTUAL_FRIEND_WEIGHTAGE_2 = 10
WORKPLACE_WEIGHTAGE_2 = 5
EDUCATION_WEIGHTAGE_2 = 5
COMMENTED_POSTS_WEIGHTAGE_2 = 10
LIKED_POSTS_WEIGHTAGE_2 = 4
COAPPEARANCE_WEIGHTAGE_2 = 10
PROFILE_VISITS_WEGIHTAGE_2 = 10
CURRENT_LOCATION_WEIGHTAGE_2 = 3
HOMETOWN_WEIGHTAGE_2 = 3
INTERESTED_IN_WEIGHTAGE = 4
SAME_LISTS_WEIGHTAGE = 8
COMMON_ACTIVITIES_WEIGHTAGE = 5
COMMON_INTERESTS_WEIGHTAGE =  5
COMMON_SPORTS_WEIGHTAGE = 2
COMMON_GAMES_WEIGHTAGE = 2
COMMON_TEAMS_WEIGHTAGE = 2
COMMON_MUSICS_WEIGHTAGE = 2
COMMON_MOVIES_WEIGHTAGE = 2
COMMON_LANGUAGES_WEIGHTAGE = 2
COMMON_TV_SHOWS_WEIGHTAGE = 2
COMMON_BOOKS_WEIGHTAGE = 2
COMMON_ATHLETES_WEIGHTAGE = 2


MUTUAL_FRIENDS_PER_PAGE = 1
NUM_AUTOCOMPLETE_TAGGED_USERS = 10


FEED_TYPE_POST = "post"
FEED_TYPE_LIKE = "like"
FEED_TYPE_COMMENT = "comment"
FEED_TYPE_SHARE = "share"
FEED_TYPE_TAG = "tag"
FEED_TYPE_FRIEND = "friend"
FEED_TYPE_HOMETOWN_CHANGE = "hometown"
FEED_TYPE_CURR_LOCATION_CHANGE = "curr_location"
FEED_TYPE_RELATIONSHIP_STATUS_CHANGE = "rel_status"
FEED_TYPE_EDUCATION_CHANGE = "education"
FEED_TYPE_WORKPLACE_CHANGE = "workplace"


#TOP STORIES ALGORITHM
DEFAULT_SCORE_ADDED_FRIEND = 15 #based on the past average scores of feed
NUM_TOP_FRIENDS = 5
WEIGHTAGE_TOP_FRIEND_ACTIVITY = 1.5
WEIGHTAGE_COMMENTS = 1.5
WEIGHTAGE_TAGS = 2
WEIGHTAGE_LIKES = 1
